#!/usr/bin/env bash
set -e

# ensure user belongs to sudo group
if ! groups $(whoami) | grep -q sudo; then
  echo "Adding user to sudo group"
  sudo usermod -aG sudo $(whoami) &> /dev/null
  echo "\nYOU MUST RELOGIN TO CONTINUE INSTALLATION"
  exit 0
fi

CONFIG="install.conf.yaml"
DOTBOT_DIR="dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
