#!/bin/bash
if [ ! -d "${HOME}/.vim/colors" ]; then
  echo "[install-colors] installing: .vim/colors"
  mkdir -p "${HOME}/.vim/colors"
  wget https://github.com/daylerees/colour-schemes/archive/master.zip
  wget https://raw.githubusercontent.com/altercation/vim-colors-solarized/master/colors/solarized.vim
  unzip master.zip
  mv colour-schemes-master/vim/colors/* "${HOME}/.vim/colors"
  mv solarized.vim "${HOME}/.vim/colors"
  rm -rf master.zip colour-schemes-master
else
  echo "[install-colors] skipping: .vim/colors already exists"
fi
