filetype plugin on
filetype indent on

" only use spaces for indentation
set expandtab
set softtabstop=2
set shiftwidth=2

set number
set shellslash

set pastetoggle=<F2>

" http://vim-latex.sourceforge.net/documentation/latex-suite.html#recommended-settings
set grepprg=grep\ -nH\ $*
let g:tex_flavor='latex'

" Allow pasting to multiple locations.
" 'p' to paste, 'gv' to re-select text original intended for copying, 'y'
" to copy again.
xnoremap p pgvy

" Highlight text that exceeds the 80 column limit.
" TODO: Doesn't work anymore
" highlight OverLength ctermbg=darkred ctermfg=white
" match OverLength /\%81v.\+/

" netrw
let g:netrw_liststyle=3

" spelling
" set spell spelllang=en_gb

" Kill the bells on Cygwin
set vb
set t_vb=

" Colours!
syntax enable
set hlsearch " highlight all search matches
" set t_Co=256
" colo hydrangea
" color smyck

" hi Normal ctermbg=none

" airline
set laststatus=2
set encoding=utf-8
set ttimeoutlen=50
let g:airline_powerline_fonts=1

" vim_markdown_preview
" https://github.com/JamshedVesuna/vim-markdown-preview/wiki/Use-other-browser-to-preview-markdown
" let vim_markdown_preview_browser='Firefox'
" let vim_markdown_preview_github=1
"
" let g:livedown_browser='Firefox'
" let g:livedown_open=1
" let g:livedown_autorun=1

"
let g:vim_markdown_folding_disabled=1

" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Vundle plugins
Plugin 'gmarik/Vundle.vim'
Plugin 'JuliaLang/julia-vim'
Plugin 'morhetz/gruvbox'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'hynek/vim-python-pep8-indent'
Plugin 'tpope/vim-fugitive'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-syntastic/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'junegunn/seoul256.vim'
Plugin 'JamshedVesuna/vim-markdown-preview'
Plugin 'shime/vim-livedown'
Plugin 'khzaw/vim-conceal'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'davidhalter/jedi-vim'
Plugin 'nvie/vim-flake8'
"Plugin 'vim-airline/vim-airline-themes'
"Plugin 'lervag/vimtex'
"Plugin 'yuttie/hydrangea-vim'

call vundle#end()
filetype plugin indent on

let $LOCALFILE=expand("~/.vimrc_local")
if filereadable($LOCALFILE)
  source $LOCALFILE
endif
