# setxkbmap gb

# start pulseaudio
# start-pulseaudio-x11

# fix the typematic delay (and frequency)
xset r rate 200 35

# disable screensaver
xset s off
xset -dpms
xset s noblank

# https://a3nm.net/blog/xrandr.html
# disable the built-in monitor if plugged into my monitor
xrandr -q | grep "^DP-1 connected" && xrandr --output eDP-1 --disable

# enable 144Hz on monitor
. xinitrc.local
xrandr -q | grep "USB-C-0 connected 2560x1440" \
  && xrandr --output USB-C-0 --mode 2560x1440 --rate 144.00

# autocutsel &
exec i3
