export VISUAL="vim"

[[ -f "${HOME}/.bash_functions" ]] && source "${HOME}/.bash_functions"
[[ -f "${HOME}/.bash_aliases" ]] && source "${HOME}/.bash_aliases"
[[ -f "${HOME}/.dockerfunc" ]] && source "${HOME}/.dockerfunc"

export PATH="${HOME}/.dynamic-colors/bin:${PATH}"

# initialise opam
if which opam &> /dev/null; then
  eval $(opam config env)
fi
