#
# WARNING: Depends is_ubuntu function in bash_functions
#
if is_ubuntu; then
  alias xclip='xclip -selection c'
  alias solarized-light='$HOME/.dotfiles/solarized/gnome-terminal/set_light.sh'
  alias solarized-dark='$HOME/.dotfiles/solarized/gnome-terminal/set_dark.sh'
  alias ls='ls --color'
  alias routerip="route -n | grep 'UG' | awk '{ print \$2 }'"
  alias docker-clean='docker rmi $(docker images -q --filter 'dangling=true')'
fi

# Allow aliases to be sudo-ed
alias sudo='sudo '

alias cdls='cd $1 && ls'
